export enum API_ENDPOINT {
  AUTHOR = '/authors',
  BOOK = '/books',
  BOOK_AUTHOR = '/book-authors',
  BOOK_CATEGORY = '/book-categories',
  CATEGORY = '/categories',
  EVENT = '/events',
  IMAGE = '/images',
  INVENTORY = '/inventories',
  PUBLISHER = '/publishers',
  ROLE = '/roles',
  SOUVENIR = '/souvenirs',
  STORE = '/stores',
  STREET = '/streets',
  USER = '/users',
  USER_ROLE = '/user-roles',
  USER_STORE = '/user-stores',
  ZONE = '/zones',
  PERSON = '/persons',
  ORDER = '/orders',
  ORDER_DETAILS = '/order-details',
  STORE_SCHEDULES = '/store-schedules',
  EVENT_REGISTRATION = '/event-registrations',
}
