export enum Language {
  VIETNAMESE = 'vi',
  ENGLISH = 'en',
  FRENCH = 'fr',
  GERMAN = 'de',
  SPANISH = 'es',
  CHINESE = 'zh',
  JAPANESE = 'ja',
  KOREAN = 'ko',
  RUSSIAN = 'ru',
  PORTUGUESE = 'pt',
  ITALIAN = 'it',
  ARABIC = 'ar',
  HINDI = 'hi',
  THAI = 'th',
}

export const LANGUAGE_VALUES = [
  Language.VIETNAMESE,
  Language.ENGLISH,
  Language.FRENCH,
  Language.GERMAN,
  Language.SPANISH,
  Language.CHINESE,
  Language.JAPANESE,
  Language.KOREAN,
  Language.RUSSIAN,
  Language.PORTUGUESE,
  Language.ITALIAN,
  Language.ARABIC,
  Language.HINDI,
  Language.THAI,
] as const;

export const LanguageLabels: Record<Language, string> = {
  [Language.VIETNAMESE]: 'Tiếng Việt (Vietnamese)',
  [Language.ENGLISH]: 'English',
  [Language.CHINESE]: '中文 (Chinese)',
  [Language.JAPANESE]: '日本語 (Japanese)',
  [Language.KOREAN]: '한국어 (Korean)',
  [Language.RUSSIAN]: 'Русский (Russian)',
  [Language.FRENCH]: 'Français (French)',
  [Language.GERMAN]: 'Deutsch (German)',
  [Language.SPANISH]: 'Español (Spanish)',
  [Language.PORTUGUESE]: 'Português (Portuguese)',
  [Language.ITALIAN]: 'Italiano (Italian)',
  [Language.ARABIC]: 'العربية (Arabic)',
  [Language.HINDI]: 'हिन्दी (Hindi)',
  [Language.THAI]: 'ไทย (Thai)',
};

//  (Optional) Vietnamese language labels for the languages
export const VietnameseLanguageLabels: Record<Language, string> = {
  [Language.VIETNAMESE]: 'Tiếng Việt',
  [Language.ENGLISH]: 'Tiếng Anh',
  [Language.FRENCH]: 'Tiếng Pháp',
  [Language.GERMAN]: 'Tiếng Đức',
  [Language.SPANISH]: 'Tiếng Tây Ban Nha',
  [Language.CHINESE]: 'Tiếng Trung',
  [Language.JAPANESE]: 'Tiếng Nhật',
  [Language.KOREAN]: 'Tiếng Hàn',
  [Language.RUSSIAN]: 'Tiếng Nga',
  [Language.PORTUGUESE]: 'Tiếng Bồ Đào Nha',
  [Language.ITALIAN]: 'Tiếng Ý',
  [Language.ARABIC]: 'Tiếng Ả Rập',
  [Language.HINDI]: 'Tiếng Hindi',
  [Language.THAI]: 'Tiếng Thái',
};
