import { ThemeProvider } from '@/components/theme-provider';
import NextAuthProvider from '@/providers/NextAuthProvider';
import QueryProvider from '@/providers/QueryProvider';
import StoreProvider from '@/providers/StoreProvider';
import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';

const roboto = Roboto({
  subsets: ['vietnamese'],
  weight: ['400', '700'],
});

export const metadata: Metadata = {
  title: 'Smart Book Street',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${roboto.className} antialiased`}>
        <StoreProvider>
          <QueryProvider>
            <NextAuthProvider>
              <ThemeProvider
                attribute='class'
                defaultTheme='system'
                enableSystem
                disableTransitionOnChange
              >
                {children}
              </ThemeProvider>
            </NextAuthProvider>
          </QueryProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
